title: "Reeva Faisal"
# show_downloads: true
description: >
  Senior studying Data Science at University of Michigan - Ann Arbor
  Undergraduate researcher at <a href="https://neurocy.notion.site/Future-of-Programming-Lab-241d162461a04064ae1fd9ae32bf4cb1">Future of Programming Lab</a>
logo: "C7F101DE-EA91-40A2-B31A-A46A95771D58.JPEG"
github_button: true
repository: https://github.com/reevafaisal/reevafaisal.github.io
# theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme

remote_theme: vaibhavvikas/jekyll-theme-minimalistic


