title: "   Reeva Faisal   "
# show_downloads : true
description: Senior studying Data Science at University of Michigan - Ann Arbor \n\ 
Undergraduate researcher at [Future of Programming Lab](https://neurocy.notion.site/Future-of-Programming-Lab-241d162461a04064ae1fd9ae32bf4cb1) 
logo: C7F101DE-EA91-40A2-B31A-A46A95771D58.JPEG
# github_button: true

# Provide the correct repository URL
repository: https://github.com/reevafaisal/reevafaisal.github.io
theme: jekyll-theme-minimal

