title: "Reeva Faisal" 

description: > 
  Senior studying Data Science at University of Michigan - Ann Arbor
  Undergraduate researcher at <a href="https://neurocy.notion.site/Future-of-Programming-Lab-241d162461a04064ae1fd9ae32bf4cb1">Future of Programming Lab</a>
logo: "Screenshot 2024-10-13 at 4.04.46 PM_batcheditor_fotor.jpg"
email: reevaf@umich.edu
# theme: jekyll-theme-minimal
favicon: true 
plugins: 
  - jekyll-remote-theme

# plugins:
#   - jekyll-sitemap  
#   - jekyll-seo-tag
#   - jemoji
# color-scheme: light

# remote_theme: reevafaisal/hexo-theme-edinburgh
remote_theme: reevafaisal/jekyll-theme-minimalistic

# editor.find.cursorMoveOnType: false
navigation:
  - name: Future of Programming Lab
    link: ./index.html#future-of-programming-lab
  - name: Performance Predictions in TB and HIV
    link: ./index.html#performance-predictions-in-tb-and-hiv
  - name: Insta485 Client-Side Web Application
    link: ./index.html#insta485-client-side-web-application
  - name: Data Retrieval and Parsing using Web Scraping and APIs
    link: ./index.html#data-retrieval-and-parsing-using-web-scraping-and-apis
  - name: EDA and Visualizations Toolkit
    link: ./index.html#eda-and-visualizations-toolkit
  - name: Travelling Salesman Problem
    link: ./index.html#travelling-salesman-problem
  # - name: Pixel Crafter
  #   link: ./index.html#pixel-crafter
  # - name: Insta485 Client-Side Web Application
  #   link: ./index.html#Insta485 Client-Side Web Application 
