title: Reeva Faisal
description: Senior studying Data Science at University of Michigan - Ann Arbor | Current undergraduate researcher at FP Lab.
logo: "Screenshot 2024-10-13 at 2.41.21 PM-modified (1).png"
# github_button: true

# Provide the correct repository URL
repository: https://github.com/reevafaisal/reevafaisal.github.io
theme: jekyll-theme-minimal

