title: Reeva Faisal
description: |
Senior studying Data Science at University of Michigan - Ann Arbor    
Current undergraduate researcher at FP Lab.
github_button: true

# Provide the correct repository URL
repository: https://github.com/reevafaisal/reevafaisal.github.io
theme: jekyll-theme-cayman
