title: "Reeva Faisal"
# show_downloads: true
description: >
  Senior studying Data Science at University of Michigan - Ann Arbor
  Undergraduate researcher at <a href="https://neurocy.notion.site/Future-of-Programming-Lab-241d162461a04064ae1fd9ae32bf4cb1">Future of Programming Lab</a>
logo: "Screenshot 2024-10-13 at 4.04.46 PM_batcheditor_fotor.jpg"
github_button: true
repository: https://github.com/reevafaisal/reevafaisal.github.io
# theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
color-scheme: light

remote_theme: vaibhavvikas/jekyll-theme-minimalistic
platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/reevafaisal
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/reeva-faisal/
 - name: Email
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:reevaf@umich.com
